name: Measure coverage

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and run tests with JaCoCo
        env:
          APPLICATION_TEST_PROPERTIES: "src/main/resources/application-test.properties"
        run: |
          mvn clean verify -Dspring.config.location="$APPLICATION_TEST_PROPERTIES"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Check coverage thresholds
        run: |
          COVERAGE=$(sed -n 's/.*<counter.*type="LINE".*covered="\([0-9]*\)".*missed="\([0-9]*\)".*/\1/gp' target/site/jacoco/jacoco.xml)
          TOTAL_LINES=$(sed -n 's/.*<counter.*type="LINE".*covered="\([0-9]*\)".*missed="\([0-9]*\)".*/\2/gp' target/site/jacoco/jacoco.xml)
          COVERAGE_PERCENT=$(echo "scale=2; $COVERAGE * 100 / ($COVERAGE + $TOTAL_LINES)" | bc -l)
          THRESHOLD=80
          
          echo "COVERAGE: $COVERAGE"
          echo "TOTAL_LINES: $TOTAL_LINES"
          echo "COVERAGE_PERCENT: $COVERAGE_PERCENT"
          
          if (( $(echo "$COVERAGE_PERCENT < $THRESHOLD" | bc -l) )); then
            echo "Erro: a cobertura está abaixo do limite  ($THRESHOLD%)"
            exit 1
          elseif (( $(echo "$COVERAGE_PERCENT > $THRESHOLD" | bc -l) )); then
            echo "Coverage esta okay"
          fi
